
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Horse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Horse
 * 
 */
export type HorseModel = runtime.Types.Result.DefaultSelection<Prisma.$HorsePayload>

export type AggregateHorse = {
  _count: HorseCountAggregateOutputType | null
  _avg: HorseAvgAggregateOutputType | null
  _sum: HorseSumAggregateOutputType | null
  _min: HorseMinAggregateOutputType | null
  _max: HorseMaxAggregateOutputType | null
}

export type HorseAvgAggregateOutputType = {
  id: number | null
}

export type HorseSumAggregateOutputType = {
  id: number | null
}

export type HorseMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type HorseMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type HorseCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type HorseAvgAggregateInputType = {
  id?: true
}

export type HorseSumAggregateInputType = {
  id?: true
}

export type HorseMinAggregateInputType = {
  id?: true
  name?: true
}

export type HorseMaxAggregateInputType = {
  id?: true
  name?: true
}

export type HorseCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type HorseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Horse to aggregate.
   */
  where?: Prisma.HorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horses to fetch.
   */
  orderBy?: Prisma.HorseOrderByWithRelationInput | Prisma.HorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Horses
  **/
  _count?: true | HorseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HorseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HorseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HorseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HorseMaxAggregateInputType
}

export type GetHorseAggregateType<T extends HorseAggregateArgs> = {
      [P in keyof T & keyof AggregateHorse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHorse[P]>
    : Prisma.GetScalarType<T[P], AggregateHorse[P]>
}




export type HorseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HorseWhereInput
  orderBy?: Prisma.HorseOrderByWithAggregationInput | Prisma.HorseOrderByWithAggregationInput[]
  by: Prisma.HorseScalarFieldEnum[] | Prisma.HorseScalarFieldEnum
  having?: Prisma.HorseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HorseCountAggregateInputType | true
  _avg?: HorseAvgAggregateInputType
  _sum?: HorseSumAggregateInputType
  _min?: HorseMinAggregateInputType
  _max?: HorseMaxAggregateInputType
}

export type HorseGroupByOutputType = {
  id: number
  name: string
  _count: HorseCountAggregateOutputType | null
  _avg: HorseAvgAggregateOutputType | null
  _sum: HorseSumAggregateOutputType | null
  _min: HorseMinAggregateOutputType | null
  _max: HorseMaxAggregateOutputType | null
}

type GetHorseGroupByPayload<T extends HorseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HorseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HorseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HorseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HorseGroupByOutputType[P]>
      }
    >
  >



export type HorseWhereInput = {
  AND?: Prisma.HorseWhereInput | Prisma.HorseWhereInput[]
  OR?: Prisma.HorseWhereInput[]
  NOT?: Prisma.HorseWhereInput | Prisma.HorseWhereInput[]
  id?: Prisma.IntFilter<"Horse"> | number
  name?: Prisma.StringFilter<"Horse"> | string
  races?: Prisma.RaceHorseListRelationFilter
}

export type HorseOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  races?: Prisma.RaceHorseOrderByRelationAggregateInput
}

export type HorseWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.HorseWhereInput | Prisma.HorseWhereInput[]
  OR?: Prisma.HorseWhereInput[]
  NOT?: Prisma.HorseWhereInput | Prisma.HorseWhereInput[]
  name?: Prisma.StringFilter<"Horse"> | string
  races?: Prisma.RaceHorseListRelationFilter
}, "id">

export type HorseOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.HorseCountOrderByAggregateInput
  _avg?: Prisma.HorseAvgOrderByAggregateInput
  _max?: Prisma.HorseMaxOrderByAggregateInput
  _min?: Prisma.HorseMinOrderByAggregateInput
  _sum?: Prisma.HorseSumOrderByAggregateInput
}

export type HorseScalarWhereWithAggregatesInput = {
  AND?: Prisma.HorseScalarWhereWithAggregatesInput | Prisma.HorseScalarWhereWithAggregatesInput[]
  OR?: Prisma.HorseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HorseScalarWhereWithAggregatesInput | Prisma.HorseScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Horse"> | number
  name?: Prisma.StringWithAggregatesFilter<"Horse"> | string
}

export type HorseCreateInput = {
  name: string
  races?: Prisma.RaceHorseCreateNestedManyWithoutHorseInput
}

export type HorseUncheckedCreateInput = {
  id?: number
  name: string
  races?: Prisma.RaceHorseUncheckedCreateNestedManyWithoutHorseInput
}

export type HorseUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  races?: Prisma.RaceHorseUpdateManyWithoutHorseNestedInput
}

export type HorseUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  races?: Prisma.RaceHorseUncheckedUpdateManyWithoutHorseNestedInput
}

export type HorseCreateManyInput = {
  id?: number
  name: string
}

export type HorseUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HorseUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HorseCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type HorseAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type HorseMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type HorseMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type HorseSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type HorseScalarRelationFilter = {
  is?: Prisma.HorseWhereInput
  isNot?: Prisma.HorseWhereInput
}

export type HorseCreateNestedOneWithoutRacesInput = {
  create?: Prisma.XOR<Prisma.HorseCreateWithoutRacesInput, Prisma.HorseUncheckedCreateWithoutRacesInput>
  connectOrCreate?: Prisma.HorseCreateOrConnectWithoutRacesInput
  connect?: Prisma.HorseWhereUniqueInput
}

export type HorseUpdateOneRequiredWithoutRacesNestedInput = {
  create?: Prisma.XOR<Prisma.HorseCreateWithoutRacesInput, Prisma.HorseUncheckedCreateWithoutRacesInput>
  connectOrCreate?: Prisma.HorseCreateOrConnectWithoutRacesInput
  upsert?: Prisma.HorseUpsertWithoutRacesInput
  connect?: Prisma.HorseWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.HorseUpdateToOneWithWhereWithoutRacesInput, Prisma.HorseUpdateWithoutRacesInput>, Prisma.HorseUncheckedUpdateWithoutRacesInput>
}

export type HorseCreateWithoutRacesInput = {
  name: string
}

export type HorseUncheckedCreateWithoutRacesInput = {
  id?: number
  name: string
}

export type HorseCreateOrConnectWithoutRacesInput = {
  where: Prisma.HorseWhereUniqueInput
  create: Prisma.XOR<Prisma.HorseCreateWithoutRacesInput, Prisma.HorseUncheckedCreateWithoutRacesInput>
}

export type HorseUpsertWithoutRacesInput = {
  update: Prisma.XOR<Prisma.HorseUpdateWithoutRacesInput, Prisma.HorseUncheckedUpdateWithoutRacesInput>
  create: Prisma.XOR<Prisma.HorseCreateWithoutRacesInput, Prisma.HorseUncheckedCreateWithoutRacesInput>
  where?: Prisma.HorseWhereInput
}

export type HorseUpdateToOneWithWhereWithoutRacesInput = {
  where?: Prisma.HorseWhereInput
  data: Prisma.XOR<Prisma.HorseUpdateWithoutRacesInput, Prisma.HorseUncheckedUpdateWithoutRacesInput>
}

export type HorseUpdateWithoutRacesInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HorseUncheckedUpdateWithoutRacesInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type HorseCountOutputType
 */

export type HorseCountOutputType = {
  races: number
}

export type HorseCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  races?: boolean | HorseCountOutputTypeCountRacesArgs
}

/**
 * HorseCountOutputType without action
 */
export type HorseCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HorseCountOutputType
   */
  select?: Prisma.HorseCountOutputTypeSelect<ExtArgs> | null
}

/**
 * HorseCountOutputType without action
 */
export type HorseCountOutputTypeCountRacesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RaceHorseWhereInput
}


export type HorseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  races?: boolean | Prisma.Horse$racesArgs<ExtArgs>
  _count?: boolean | Prisma.HorseCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["horse"]>

export type HorseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["horse"]>

export type HorseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["horse"]>

export type HorseSelectScalar = {
  id?: boolean
  name?: boolean
}

export type HorseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["horse"]>
export type HorseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  races?: boolean | Prisma.Horse$racesArgs<ExtArgs>
  _count?: boolean | Prisma.HorseCountOutputTypeDefaultArgs<ExtArgs>
}
export type HorseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type HorseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $HorsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Horse"
  objects: {
    races: Prisma.$RaceHorsePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["horse"]>
  composites: {}
}

export type HorseGetPayload<S extends boolean | null | undefined | HorseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HorsePayload, S>

export type HorseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HorseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HorseCountAggregateInputType | true
  }

export interface HorseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Horse'], meta: { name: 'Horse' } }
  /**
   * Find zero or one Horse that matches the filter.
   * @param {HorseFindUniqueArgs} args - Arguments to find a Horse
   * @example
   * // Get one Horse
   * const horse = await prisma.horse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HorseFindUniqueArgs>(args: Prisma.SelectSubset<T, HorseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Horse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HorseFindUniqueOrThrowArgs} args - Arguments to find a Horse
   * @example
   * // Get one Horse
   * const horse = await prisma.horse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HorseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HorseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Horse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseFindFirstArgs} args - Arguments to find a Horse
   * @example
   * // Get one Horse
   * const horse = await prisma.horse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HorseFindFirstArgs>(args?: Prisma.SelectSubset<T, HorseFindFirstArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Horse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseFindFirstOrThrowArgs} args - Arguments to find a Horse
   * @example
   * // Get one Horse
   * const horse = await prisma.horse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HorseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HorseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Horses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Horses
   * const horses = await prisma.horse.findMany()
   * 
   * // Get first 10 Horses
   * const horses = await prisma.horse.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const horseWithIdOnly = await prisma.horse.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HorseFindManyArgs>(args?: Prisma.SelectSubset<T, HorseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Horse.
   * @param {HorseCreateArgs} args - Arguments to create a Horse.
   * @example
   * // Create one Horse
   * const Horse = await prisma.horse.create({
   *   data: {
   *     // ... data to create a Horse
   *   }
   * })
   * 
   */
  create<T extends HorseCreateArgs>(args: Prisma.SelectSubset<T, HorseCreateArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Horses.
   * @param {HorseCreateManyArgs} args - Arguments to create many Horses.
   * @example
   * // Create many Horses
   * const horse = await prisma.horse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HorseCreateManyArgs>(args?: Prisma.SelectSubset<T, HorseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Horses and returns the data saved in the database.
   * @param {HorseCreateManyAndReturnArgs} args - Arguments to create many Horses.
   * @example
   * // Create many Horses
   * const horse = await prisma.horse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Horses and only return the `id`
   * const horseWithIdOnly = await prisma.horse.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HorseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HorseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Horse.
   * @param {HorseDeleteArgs} args - Arguments to delete one Horse.
   * @example
   * // Delete one Horse
   * const Horse = await prisma.horse.delete({
   *   where: {
   *     // ... filter to delete one Horse
   *   }
   * })
   * 
   */
  delete<T extends HorseDeleteArgs>(args: Prisma.SelectSubset<T, HorseDeleteArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Horse.
   * @param {HorseUpdateArgs} args - Arguments to update one Horse.
   * @example
   * // Update one Horse
   * const horse = await prisma.horse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HorseUpdateArgs>(args: Prisma.SelectSubset<T, HorseUpdateArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Horses.
   * @param {HorseDeleteManyArgs} args - Arguments to filter Horses to delete.
   * @example
   * // Delete a few Horses
   * const { count } = await prisma.horse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HorseDeleteManyArgs>(args?: Prisma.SelectSubset<T, HorseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Horses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Horses
   * const horse = await prisma.horse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HorseUpdateManyArgs>(args: Prisma.SelectSubset<T, HorseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Horses and returns the data updated in the database.
   * @param {HorseUpdateManyAndReturnArgs} args - Arguments to update many Horses.
   * @example
   * // Update many Horses
   * const horse = await prisma.horse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Horses and only return the `id`
   * const horseWithIdOnly = await prisma.horse.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HorseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HorseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Horse.
   * @param {HorseUpsertArgs} args - Arguments to update or create a Horse.
   * @example
   * // Update or create a Horse
   * const horse = await prisma.horse.upsert({
   *   create: {
   *     // ... data to create a Horse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Horse we want to update
   *   }
   * })
   */
  upsert<T extends HorseUpsertArgs>(args: Prisma.SelectSubset<T, HorseUpsertArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Horses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseCountArgs} args - Arguments to filter Horses to count.
   * @example
   * // Count the number of Horses
   * const count = await prisma.horse.count({
   *   where: {
   *     // ... the filter for the Horses we want to count
   *   }
   * })
  **/
  count<T extends HorseCountArgs>(
    args?: Prisma.Subset<T, HorseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HorseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Horse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HorseAggregateArgs>(args: Prisma.Subset<T, HorseAggregateArgs>): Prisma.PrismaPromise<GetHorseAggregateType<T>>

  /**
   * Group by Horse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HorseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HorseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HorseGroupByArgs['orderBy'] }
      : { orderBy?: HorseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HorseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHorseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Horse model
 */
readonly fields: HorseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Horse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HorseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  races<T extends Prisma.Horse$racesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Horse$racesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Horse model
 */
export interface HorseFieldRefs {
  readonly id: Prisma.FieldRef<"Horse", 'Int'>
  readonly name: Prisma.FieldRef<"Horse", 'String'>
}
    

// Custom InputTypes
/**
 * Horse findUnique
 */
export type HorseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * Filter, which Horse to fetch.
   */
  where: Prisma.HorseWhereUniqueInput
}

/**
 * Horse findUniqueOrThrow
 */
export type HorseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * Filter, which Horse to fetch.
   */
  where: Prisma.HorseWhereUniqueInput
}

/**
 * Horse findFirst
 */
export type HorseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * Filter, which Horse to fetch.
   */
  where?: Prisma.HorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horses to fetch.
   */
  orderBy?: Prisma.HorseOrderByWithRelationInput | Prisma.HorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Horses.
   */
  cursor?: Prisma.HorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Horses.
   */
  distinct?: Prisma.HorseScalarFieldEnum | Prisma.HorseScalarFieldEnum[]
}

/**
 * Horse findFirstOrThrow
 */
export type HorseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * Filter, which Horse to fetch.
   */
  where?: Prisma.HorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horses to fetch.
   */
  orderBy?: Prisma.HorseOrderByWithRelationInput | Prisma.HorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Horses.
   */
  cursor?: Prisma.HorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Horses.
   */
  distinct?: Prisma.HorseScalarFieldEnum | Prisma.HorseScalarFieldEnum[]
}

/**
 * Horse findMany
 */
export type HorseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * Filter, which Horses to fetch.
   */
  where?: Prisma.HorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Horses to fetch.
   */
  orderBy?: Prisma.HorseOrderByWithRelationInput | Prisma.HorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Horses.
   */
  cursor?: Prisma.HorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Horses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Horses.
   */
  skip?: number
  distinct?: Prisma.HorseScalarFieldEnum | Prisma.HorseScalarFieldEnum[]
}

/**
 * Horse create
 */
export type HorseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * The data needed to create a Horse.
   */
  data: Prisma.XOR<Prisma.HorseCreateInput, Prisma.HorseUncheckedCreateInput>
}

/**
 * Horse createMany
 */
export type HorseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Horses.
   */
  data: Prisma.HorseCreateManyInput | Prisma.HorseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Horse createManyAndReturn
 */
export type HorseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * The data used to create many Horses.
   */
  data: Prisma.HorseCreateManyInput | Prisma.HorseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Horse update
 */
export type HorseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * The data needed to update a Horse.
   */
  data: Prisma.XOR<Prisma.HorseUpdateInput, Prisma.HorseUncheckedUpdateInput>
  /**
   * Choose, which Horse to update.
   */
  where: Prisma.HorseWhereUniqueInput
}

/**
 * Horse updateMany
 */
export type HorseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Horses.
   */
  data: Prisma.XOR<Prisma.HorseUpdateManyMutationInput, Prisma.HorseUncheckedUpdateManyInput>
  /**
   * Filter which Horses to update
   */
  where?: Prisma.HorseWhereInput
  /**
   * Limit how many Horses to update.
   */
  limit?: number
}

/**
 * Horse updateManyAndReturn
 */
export type HorseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * The data used to update Horses.
   */
  data: Prisma.XOR<Prisma.HorseUpdateManyMutationInput, Prisma.HorseUncheckedUpdateManyInput>
  /**
   * Filter which Horses to update
   */
  where?: Prisma.HorseWhereInput
  /**
   * Limit how many Horses to update.
   */
  limit?: number
}

/**
 * Horse upsert
 */
export type HorseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * The filter to search for the Horse to update in case it exists.
   */
  where: Prisma.HorseWhereUniqueInput
  /**
   * In case the Horse found by the `where` argument doesn't exist, create a new Horse with this data.
   */
  create: Prisma.XOR<Prisma.HorseCreateInput, Prisma.HorseUncheckedCreateInput>
  /**
   * In case the Horse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HorseUpdateInput, Prisma.HorseUncheckedUpdateInput>
}

/**
 * Horse delete
 */
export type HorseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
  /**
   * Filter which Horse to delete.
   */
  where: Prisma.HorseWhereUniqueInput
}

/**
 * Horse deleteMany
 */
export type HorseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Horses to delete
   */
  where?: Prisma.HorseWhereInput
  /**
   * Limit how many Horses to delete.
   */
  limit?: number
}

/**
 * Horse.races
 */
export type Horse$racesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  where?: Prisma.RaceHorseWhereInput
  orderBy?: Prisma.RaceHorseOrderByWithRelationInput | Prisma.RaceHorseOrderByWithRelationInput[]
  cursor?: Prisma.RaceHorseWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.RaceHorseScalarFieldEnum | Prisma.RaceHorseScalarFieldEnum[]
}

/**
 * Horse without action
 */
export type HorseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Horse
   */
  select?: Prisma.HorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Horse
   */
  omit?: Prisma.HorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HorseInclude<ExtArgs> | null
}
