
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `RaceHorse` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model RaceHorse
 * 
 */
export type RaceHorseModel = runtime.Types.Result.DefaultSelection<Prisma.$RaceHorsePayload>

export type AggregateRaceHorse = {
  _count: RaceHorseCountAggregateOutputType | null
  _avg: RaceHorseAvgAggregateOutputType | null
  _sum: RaceHorseSumAggregateOutputType | null
  _min: RaceHorseMinAggregateOutputType | null
  _max: RaceHorseMaxAggregateOutputType | null
}

export type RaceHorseAvgAggregateOutputType = {
  raceId: number | null
  horseId: number | null
  position: number | null
}

export type RaceHorseSumAggregateOutputType = {
  raceId: number | null
  horseId: number | null
  position: number | null
}

export type RaceHorseMinAggregateOutputType = {
  raceId: number | null
  horseId: number | null
  position: number | null
}

export type RaceHorseMaxAggregateOutputType = {
  raceId: number | null
  horseId: number | null
  position: number | null
}

export type RaceHorseCountAggregateOutputType = {
  raceId: number
  horseId: number
  position: number
  _all: number
}


export type RaceHorseAvgAggregateInputType = {
  raceId?: true
  horseId?: true
  position?: true
}

export type RaceHorseSumAggregateInputType = {
  raceId?: true
  horseId?: true
  position?: true
}

export type RaceHorseMinAggregateInputType = {
  raceId?: true
  horseId?: true
  position?: true
}

export type RaceHorseMaxAggregateInputType = {
  raceId?: true
  horseId?: true
  position?: true
}

export type RaceHorseCountAggregateInputType = {
  raceId?: true
  horseId?: true
  position?: true
  _all?: true
}

export type RaceHorseAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RaceHorse to aggregate.
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaceHorses to fetch.
   */
  orderBy?: Prisma.RaceHorseOrderByWithRelationInput | Prisma.RaceHorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RaceHorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaceHorses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaceHorses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RaceHorses
  **/
  _count?: true | RaceHorseCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: RaceHorseAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: RaceHorseSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RaceHorseMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RaceHorseMaxAggregateInputType
}

export type GetRaceHorseAggregateType<T extends RaceHorseAggregateArgs> = {
      [P in keyof T & keyof AggregateRaceHorse]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRaceHorse[P]>
    : Prisma.GetScalarType<T[P], AggregateRaceHorse[P]>
}




export type RaceHorseGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RaceHorseWhereInput
  orderBy?: Prisma.RaceHorseOrderByWithAggregationInput | Prisma.RaceHorseOrderByWithAggregationInput[]
  by: Prisma.RaceHorseScalarFieldEnum[] | Prisma.RaceHorseScalarFieldEnum
  having?: Prisma.RaceHorseScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RaceHorseCountAggregateInputType | true
  _avg?: RaceHorseAvgAggregateInputType
  _sum?: RaceHorseSumAggregateInputType
  _min?: RaceHorseMinAggregateInputType
  _max?: RaceHorseMaxAggregateInputType
}

export type RaceHorseGroupByOutputType = {
  raceId: number
  horseId: number
  position: number
  _count: RaceHorseCountAggregateOutputType | null
  _avg: RaceHorseAvgAggregateOutputType | null
  _sum: RaceHorseSumAggregateOutputType | null
  _min: RaceHorseMinAggregateOutputType | null
  _max: RaceHorseMaxAggregateOutputType | null
}

type GetRaceHorseGroupByPayload<T extends RaceHorseGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RaceHorseGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RaceHorseGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RaceHorseGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RaceHorseGroupByOutputType[P]>
      }
    >
  >



export type RaceHorseWhereInput = {
  AND?: Prisma.RaceHorseWhereInput | Prisma.RaceHorseWhereInput[]
  OR?: Prisma.RaceHorseWhereInput[]
  NOT?: Prisma.RaceHorseWhereInput | Prisma.RaceHorseWhereInput[]
  raceId?: Prisma.IntFilter<"RaceHorse"> | number
  horseId?: Prisma.IntFilter<"RaceHorse"> | number
  position?: Prisma.IntFilter<"RaceHorse"> | number
  race?: Prisma.XOR<Prisma.RaceScalarRelationFilter, Prisma.RaceWhereInput>
  horse?: Prisma.XOR<Prisma.HorseScalarRelationFilter, Prisma.HorseWhereInput>
}

export type RaceHorseOrderByWithRelationInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  race?: Prisma.RaceOrderByWithRelationInput
  horse?: Prisma.HorseOrderByWithRelationInput
}

export type RaceHorseWhereUniqueInput = Prisma.AtLeast<{
  raceId_position?: Prisma.RaceHorseRaceIdPositionCompoundUniqueInput
  raceId_horseId?: Prisma.RaceHorseRaceIdHorseIdCompoundUniqueInput
  AND?: Prisma.RaceHorseWhereInput | Prisma.RaceHorseWhereInput[]
  OR?: Prisma.RaceHorseWhereInput[]
  NOT?: Prisma.RaceHorseWhereInput | Prisma.RaceHorseWhereInput[]
  raceId?: Prisma.IntFilter<"RaceHorse"> | number
  horseId?: Prisma.IntFilter<"RaceHorse"> | number
  position?: Prisma.IntFilter<"RaceHorse"> | number
  race?: Prisma.XOR<Prisma.RaceScalarRelationFilter, Prisma.RaceWhereInput>
  horse?: Prisma.XOR<Prisma.HorseScalarRelationFilter, Prisma.HorseWhereInput>
}, "raceId_horseId" | "raceId_position">

export type RaceHorseOrderByWithAggregationInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
  _count?: Prisma.RaceHorseCountOrderByAggregateInput
  _avg?: Prisma.RaceHorseAvgOrderByAggregateInput
  _max?: Prisma.RaceHorseMaxOrderByAggregateInput
  _min?: Prisma.RaceHorseMinOrderByAggregateInput
  _sum?: Prisma.RaceHorseSumOrderByAggregateInput
}

export type RaceHorseScalarWhereWithAggregatesInput = {
  AND?: Prisma.RaceHorseScalarWhereWithAggregatesInput | Prisma.RaceHorseScalarWhereWithAggregatesInput[]
  OR?: Prisma.RaceHorseScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RaceHorseScalarWhereWithAggregatesInput | Prisma.RaceHorseScalarWhereWithAggregatesInput[]
  raceId?: Prisma.IntWithAggregatesFilter<"RaceHorse"> | number
  horseId?: Prisma.IntWithAggregatesFilter<"RaceHorse"> | number
  position?: Prisma.IntWithAggregatesFilter<"RaceHorse"> | number
}

export type RaceHorseCreateInput = {
  position: number
  race: Prisma.RaceCreateNestedOneWithoutHorsesInput
  horse: Prisma.HorseCreateNestedOneWithoutRacesInput
}

export type RaceHorseUncheckedCreateInput = {
  raceId: number
  horseId: number
  position: number
}

export type RaceHorseUpdateInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  race?: Prisma.RaceUpdateOneRequiredWithoutHorsesNestedInput
  horse?: Prisma.HorseUpdateOneRequiredWithoutRacesNestedInput
}

export type RaceHorseUncheckedUpdateInput = {
  raceId?: Prisma.IntFieldUpdateOperationsInput | number
  horseId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RaceHorseCreateManyInput = {
  raceId: number
  horseId: number
  position: number
}

export type RaceHorseUpdateManyMutationInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RaceHorseUncheckedUpdateManyInput = {
  raceId?: Prisma.IntFieldUpdateOperationsInput | number
  horseId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RaceHorseListRelationFilter = {
  every?: Prisma.RaceHorseWhereInput
  some?: Prisma.RaceHorseWhereInput
  none?: Prisma.RaceHorseWhereInput
}

export type RaceHorseOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RaceHorseRaceIdPositionCompoundUniqueInput = {
  raceId: number
  position: number
}

export type RaceHorseRaceIdHorseIdCompoundUniqueInput = {
  raceId: number
  horseId: number
}

export type RaceHorseCountOrderByAggregateInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type RaceHorseAvgOrderByAggregateInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type RaceHorseMaxOrderByAggregateInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type RaceHorseMinOrderByAggregateInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type RaceHorseSumOrderByAggregateInput = {
  raceId?: Prisma.SortOrder
  horseId?: Prisma.SortOrder
  position?: Prisma.SortOrder
}

export type RaceHorseCreateNestedManyWithoutRaceInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutRaceInput, Prisma.RaceHorseUncheckedCreateWithoutRaceInput> | Prisma.RaceHorseCreateWithoutRaceInput[] | Prisma.RaceHorseUncheckedCreateWithoutRaceInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutRaceInput | Prisma.RaceHorseCreateOrConnectWithoutRaceInput[]
  createMany?: Prisma.RaceHorseCreateManyRaceInputEnvelope
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
}

export type RaceHorseUncheckedCreateNestedManyWithoutRaceInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutRaceInput, Prisma.RaceHorseUncheckedCreateWithoutRaceInput> | Prisma.RaceHorseCreateWithoutRaceInput[] | Prisma.RaceHorseUncheckedCreateWithoutRaceInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutRaceInput | Prisma.RaceHorseCreateOrConnectWithoutRaceInput[]
  createMany?: Prisma.RaceHorseCreateManyRaceInputEnvelope
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
}

export type RaceHorseUpdateManyWithoutRaceNestedInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutRaceInput, Prisma.RaceHorseUncheckedCreateWithoutRaceInput> | Prisma.RaceHorseCreateWithoutRaceInput[] | Prisma.RaceHorseUncheckedCreateWithoutRaceInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutRaceInput | Prisma.RaceHorseCreateOrConnectWithoutRaceInput[]
  upsert?: Prisma.RaceHorseUpsertWithWhereUniqueWithoutRaceInput | Prisma.RaceHorseUpsertWithWhereUniqueWithoutRaceInput[]
  createMany?: Prisma.RaceHorseCreateManyRaceInputEnvelope
  set?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  disconnect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  delete?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  update?: Prisma.RaceHorseUpdateWithWhereUniqueWithoutRaceInput | Prisma.RaceHorseUpdateWithWhereUniqueWithoutRaceInput[]
  updateMany?: Prisma.RaceHorseUpdateManyWithWhereWithoutRaceInput | Prisma.RaceHorseUpdateManyWithWhereWithoutRaceInput[]
  deleteMany?: Prisma.RaceHorseScalarWhereInput | Prisma.RaceHorseScalarWhereInput[]
}

export type RaceHorseUncheckedUpdateManyWithoutRaceNestedInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutRaceInput, Prisma.RaceHorseUncheckedCreateWithoutRaceInput> | Prisma.RaceHorseCreateWithoutRaceInput[] | Prisma.RaceHorseUncheckedCreateWithoutRaceInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutRaceInput | Prisma.RaceHorseCreateOrConnectWithoutRaceInput[]
  upsert?: Prisma.RaceHorseUpsertWithWhereUniqueWithoutRaceInput | Prisma.RaceHorseUpsertWithWhereUniqueWithoutRaceInput[]
  createMany?: Prisma.RaceHorseCreateManyRaceInputEnvelope
  set?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  disconnect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  delete?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  update?: Prisma.RaceHorseUpdateWithWhereUniqueWithoutRaceInput | Prisma.RaceHorseUpdateWithWhereUniqueWithoutRaceInput[]
  updateMany?: Prisma.RaceHorseUpdateManyWithWhereWithoutRaceInput | Prisma.RaceHorseUpdateManyWithWhereWithoutRaceInput[]
  deleteMany?: Prisma.RaceHorseScalarWhereInput | Prisma.RaceHorseScalarWhereInput[]
}

export type RaceHorseCreateNestedManyWithoutHorseInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutHorseInput, Prisma.RaceHorseUncheckedCreateWithoutHorseInput> | Prisma.RaceHorseCreateWithoutHorseInput[] | Prisma.RaceHorseUncheckedCreateWithoutHorseInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutHorseInput | Prisma.RaceHorseCreateOrConnectWithoutHorseInput[]
  createMany?: Prisma.RaceHorseCreateManyHorseInputEnvelope
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
}

export type RaceHorseUncheckedCreateNestedManyWithoutHorseInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutHorseInput, Prisma.RaceHorseUncheckedCreateWithoutHorseInput> | Prisma.RaceHorseCreateWithoutHorseInput[] | Prisma.RaceHorseUncheckedCreateWithoutHorseInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutHorseInput | Prisma.RaceHorseCreateOrConnectWithoutHorseInput[]
  createMany?: Prisma.RaceHorseCreateManyHorseInputEnvelope
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
}

export type RaceHorseUpdateManyWithoutHorseNestedInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutHorseInput, Prisma.RaceHorseUncheckedCreateWithoutHorseInput> | Prisma.RaceHorseCreateWithoutHorseInput[] | Prisma.RaceHorseUncheckedCreateWithoutHorseInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutHorseInput | Prisma.RaceHorseCreateOrConnectWithoutHorseInput[]
  upsert?: Prisma.RaceHorseUpsertWithWhereUniqueWithoutHorseInput | Prisma.RaceHorseUpsertWithWhereUniqueWithoutHorseInput[]
  createMany?: Prisma.RaceHorseCreateManyHorseInputEnvelope
  set?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  disconnect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  delete?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  update?: Prisma.RaceHorseUpdateWithWhereUniqueWithoutHorseInput | Prisma.RaceHorseUpdateWithWhereUniqueWithoutHorseInput[]
  updateMany?: Prisma.RaceHorseUpdateManyWithWhereWithoutHorseInput | Prisma.RaceHorseUpdateManyWithWhereWithoutHorseInput[]
  deleteMany?: Prisma.RaceHorseScalarWhereInput | Prisma.RaceHorseScalarWhereInput[]
}

export type RaceHorseUncheckedUpdateManyWithoutHorseNestedInput = {
  create?: Prisma.XOR<Prisma.RaceHorseCreateWithoutHorseInput, Prisma.RaceHorseUncheckedCreateWithoutHorseInput> | Prisma.RaceHorseCreateWithoutHorseInput[] | Prisma.RaceHorseUncheckedCreateWithoutHorseInput[]
  connectOrCreate?: Prisma.RaceHorseCreateOrConnectWithoutHorseInput | Prisma.RaceHorseCreateOrConnectWithoutHorseInput[]
  upsert?: Prisma.RaceHorseUpsertWithWhereUniqueWithoutHorseInput | Prisma.RaceHorseUpsertWithWhereUniqueWithoutHorseInput[]
  createMany?: Prisma.RaceHorseCreateManyHorseInputEnvelope
  set?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  disconnect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  delete?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  connect?: Prisma.RaceHorseWhereUniqueInput | Prisma.RaceHorseWhereUniqueInput[]
  update?: Prisma.RaceHorseUpdateWithWhereUniqueWithoutHorseInput | Prisma.RaceHorseUpdateWithWhereUniqueWithoutHorseInput[]
  updateMany?: Prisma.RaceHorseUpdateManyWithWhereWithoutHorseInput | Prisma.RaceHorseUpdateManyWithWhereWithoutHorseInput[]
  deleteMany?: Prisma.RaceHorseScalarWhereInput | Prisma.RaceHorseScalarWhereInput[]
}

export type RaceHorseCreateWithoutRaceInput = {
  position: number
  horse: Prisma.HorseCreateNestedOneWithoutRacesInput
}

export type RaceHorseUncheckedCreateWithoutRaceInput = {
  horseId: number
  position: number
}

export type RaceHorseCreateOrConnectWithoutRaceInput = {
  where: Prisma.RaceHorseWhereUniqueInput
  create: Prisma.XOR<Prisma.RaceHorseCreateWithoutRaceInput, Prisma.RaceHorseUncheckedCreateWithoutRaceInput>
}

export type RaceHorseCreateManyRaceInputEnvelope = {
  data: Prisma.RaceHorseCreateManyRaceInput | Prisma.RaceHorseCreateManyRaceInput[]
  skipDuplicates?: boolean
}

export type RaceHorseUpsertWithWhereUniqueWithoutRaceInput = {
  where: Prisma.RaceHorseWhereUniqueInput
  update: Prisma.XOR<Prisma.RaceHorseUpdateWithoutRaceInput, Prisma.RaceHorseUncheckedUpdateWithoutRaceInput>
  create: Prisma.XOR<Prisma.RaceHorseCreateWithoutRaceInput, Prisma.RaceHorseUncheckedCreateWithoutRaceInput>
}

export type RaceHorseUpdateWithWhereUniqueWithoutRaceInput = {
  where: Prisma.RaceHorseWhereUniqueInput
  data: Prisma.XOR<Prisma.RaceHorseUpdateWithoutRaceInput, Prisma.RaceHorseUncheckedUpdateWithoutRaceInput>
}

export type RaceHorseUpdateManyWithWhereWithoutRaceInput = {
  where: Prisma.RaceHorseScalarWhereInput
  data: Prisma.XOR<Prisma.RaceHorseUpdateManyMutationInput, Prisma.RaceHorseUncheckedUpdateManyWithoutRaceInput>
}

export type RaceHorseScalarWhereInput = {
  AND?: Prisma.RaceHorseScalarWhereInput | Prisma.RaceHorseScalarWhereInput[]
  OR?: Prisma.RaceHorseScalarWhereInput[]
  NOT?: Prisma.RaceHorseScalarWhereInput | Prisma.RaceHorseScalarWhereInput[]
  raceId?: Prisma.IntFilter<"RaceHorse"> | number
  horseId?: Prisma.IntFilter<"RaceHorse"> | number
  position?: Prisma.IntFilter<"RaceHorse"> | number
}

export type RaceHorseCreateWithoutHorseInput = {
  position: number
  race: Prisma.RaceCreateNestedOneWithoutHorsesInput
}

export type RaceHorseUncheckedCreateWithoutHorseInput = {
  raceId: number
  position: number
}

export type RaceHorseCreateOrConnectWithoutHorseInput = {
  where: Prisma.RaceHorseWhereUniqueInput
  create: Prisma.XOR<Prisma.RaceHorseCreateWithoutHorseInput, Prisma.RaceHorseUncheckedCreateWithoutHorseInput>
}

export type RaceHorseCreateManyHorseInputEnvelope = {
  data: Prisma.RaceHorseCreateManyHorseInput | Prisma.RaceHorseCreateManyHorseInput[]
  skipDuplicates?: boolean
}

export type RaceHorseUpsertWithWhereUniqueWithoutHorseInput = {
  where: Prisma.RaceHorseWhereUniqueInput
  update: Prisma.XOR<Prisma.RaceHorseUpdateWithoutHorseInput, Prisma.RaceHorseUncheckedUpdateWithoutHorseInput>
  create: Prisma.XOR<Prisma.RaceHorseCreateWithoutHorseInput, Prisma.RaceHorseUncheckedCreateWithoutHorseInput>
}

export type RaceHorseUpdateWithWhereUniqueWithoutHorseInput = {
  where: Prisma.RaceHorseWhereUniqueInput
  data: Prisma.XOR<Prisma.RaceHorseUpdateWithoutHorseInput, Prisma.RaceHorseUncheckedUpdateWithoutHorseInput>
}

export type RaceHorseUpdateManyWithWhereWithoutHorseInput = {
  where: Prisma.RaceHorseScalarWhereInput
  data: Prisma.XOR<Prisma.RaceHorseUpdateManyMutationInput, Prisma.RaceHorseUncheckedUpdateManyWithoutHorseInput>
}

export type RaceHorseCreateManyRaceInput = {
  horseId: number
  position: number
}

export type RaceHorseUpdateWithoutRaceInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  horse?: Prisma.HorseUpdateOneRequiredWithoutRacesNestedInput
}

export type RaceHorseUncheckedUpdateWithoutRaceInput = {
  horseId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RaceHorseUncheckedUpdateManyWithoutRaceInput = {
  horseId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RaceHorseCreateManyHorseInput = {
  raceId: number
  position: number
}

export type RaceHorseUpdateWithoutHorseInput = {
  position?: Prisma.IntFieldUpdateOperationsInput | number
  race?: Prisma.RaceUpdateOneRequiredWithoutHorsesNestedInput
}

export type RaceHorseUncheckedUpdateWithoutHorseInput = {
  raceId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}

export type RaceHorseUncheckedUpdateManyWithoutHorseInput = {
  raceId?: Prisma.IntFieldUpdateOperationsInput | number
  position?: Prisma.IntFieldUpdateOperationsInput | number
}



export type RaceHorseSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  raceId?: boolean
  horseId?: boolean
  position?: boolean
  race?: boolean | Prisma.RaceDefaultArgs<ExtArgs>
  horse?: boolean | Prisma.HorseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["raceHorse"]>

export type RaceHorseSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  raceId?: boolean
  horseId?: boolean
  position?: boolean
  race?: boolean | Prisma.RaceDefaultArgs<ExtArgs>
  horse?: boolean | Prisma.HorseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["raceHorse"]>

export type RaceHorseSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  raceId?: boolean
  horseId?: boolean
  position?: boolean
  race?: boolean | Prisma.RaceDefaultArgs<ExtArgs>
  horse?: boolean | Prisma.HorseDefaultArgs<ExtArgs>
}, ExtArgs["result"]["raceHorse"]>

export type RaceHorseSelectScalar = {
  raceId?: boolean
  horseId?: boolean
  position?: boolean
}

export type RaceHorseOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"raceId" | "horseId" | "position", ExtArgs["result"]["raceHorse"]>
export type RaceHorseInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  race?: boolean | Prisma.RaceDefaultArgs<ExtArgs>
  horse?: boolean | Prisma.HorseDefaultArgs<ExtArgs>
}
export type RaceHorseIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  race?: boolean | Prisma.RaceDefaultArgs<ExtArgs>
  horse?: boolean | Prisma.HorseDefaultArgs<ExtArgs>
}
export type RaceHorseIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  race?: boolean | Prisma.RaceDefaultArgs<ExtArgs>
  horse?: boolean | Prisma.HorseDefaultArgs<ExtArgs>
}

export type $RaceHorsePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RaceHorse"
  objects: {
    race: Prisma.$RacePayload<ExtArgs>
    horse: Prisma.$HorsePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    raceId: number
    horseId: number
    position: number
  }, ExtArgs["result"]["raceHorse"]>
  composites: {}
}

export type RaceHorseGetPayload<S extends boolean | null | undefined | RaceHorseDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload, S>

export type RaceHorseCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RaceHorseFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: RaceHorseCountAggregateInputType | true
  }

export interface RaceHorseDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RaceHorse'], meta: { name: 'RaceHorse' } }
  /**
   * Find zero or one RaceHorse that matches the filter.
   * @param {RaceHorseFindUniqueArgs} args - Arguments to find a RaceHorse
   * @example
   * // Get one RaceHorse
   * const raceHorse = await prisma.raceHorse.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RaceHorseFindUniqueArgs>(args: Prisma.SelectSubset<T, RaceHorseFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RaceHorse that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RaceHorseFindUniqueOrThrowArgs} args - Arguments to find a RaceHorse
   * @example
   * // Get one RaceHorse
   * const raceHorse = await prisma.raceHorse.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RaceHorseFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RaceHorseFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RaceHorse that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseFindFirstArgs} args - Arguments to find a RaceHorse
   * @example
   * // Get one RaceHorse
   * const raceHorse = await prisma.raceHorse.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RaceHorseFindFirstArgs>(args?: Prisma.SelectSubset<T, RaceHorseFindFirstArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RaceHorse that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseFindFirstOrThrowArgs} args - Arguments to find a RaceHorse
   * @example
   * // Get one RaceHorse
   * const raceHorse = await prisma.raceHorse.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RaceHorseFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RaceHorseFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RaceHorses that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RaceHorses
   * const raceHorses = await prisma.raceHorse.findMany()
   * 
   * // Get first 10 RaceHorses
   * const raceHorses = await prisma.raceHorse.findMany({ take: 10 })
   * 
   * // Only select the `raceId`
   * const raceHorseWithRaceIdOnly = await prisma.raceHorse.findMany({ select: { raceId: true } })
   * 
   */
  findMany<T extends RaceHorseFindManyArgs>(args?: Prisma.SelectSubset<T, RaceHorseFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RaceHorse.
   * @param {RaceHorseCreateArgs} args - Arguments to create a RaceHorse.
   * @example
   * // Create one RaceHorse
   * const RaceHorse = await prisma.raceHorse.create({
   *   data: {
   *     // ... data to create a RaceHorse
   *   }
   * })
   * 
   */
  create<T extends RaceHorseCreateArgs>(args: Prisma.SelectSubset<T, RaceHorseCreateArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RaceHorses.
   * @param {RaceHorseCreateManyArgs} args - Arguments to create many RaceHorses.
   * @example
   * // Create many RaceHorses
   * const raceHorse = await prisma.raceHorse.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RaceHorseCreateManyArgs>(args?: Prisma.SelectSubset<T, RaceHorseCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many RaceHorses and returns the data saved in the database.
   * @param {RaceHorseCreateManyAndReturnArgs} args - Arguments to create many RaceHorses.
   * @example
   * // Create many RaceHorses
   * const raceHorse = await prisma.raceHorse.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many RaceHorses and only return the `raceId`
   * const raceHorseWithRaceIdOnly = await prisma.raceHorse.createManyAndReturn({
   *   select: { raceId: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends RaceHorseCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, RaceHorseCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a RaceHorse.
   * @param {RaceHorseDeleteArgs} args - Arguments to delete one RaceHorse.
   * @example
   * // Delete one RaceHorse
   * const RaceHorse = await prisma.raceHorse.delete({
   *   where: {
   *     // ... filter to delete one RaceHorse
   *   }
   * })
   * 
   */
  delete<T extends RaceHorseDeleteArgs>(args: Prisma.SelectSubset<T, RaceHorseDeleteArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RaceHorse.
   * @param {RaceHorseUpdateArgs} args - Arguments to update one RaceHorse.
   * @example
   * // Update one RaceHorse
   * const raceHorse = await prisma.raceHorse.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RaceHorseUpdateArgs>(args: Prisma.SelectSubset<T, RaceHorseUpdateArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RaceHorses.
   * @param {RaceHorseDeleteManyArgs} args - Arguments to filter RaceHorses to delete.
   * @example
   * // Delete a few RaceHorses
   * const { count } = await prisma.raceHorse.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RaceHorseDeleteManyArgs>(args?: Prisma.SelectSubset<T, RaceHorseDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RaceHorses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RaceHorses
   * const raceHorse = await prisma.raceHorse.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RaceHorseUpdateManyArgs>(args: Prisma.SelectSubset<T, RaceHorseUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RaceHorses and returns the data updated in the database.
   * @param {RaceHorseUpdateManyAndReturnArgs} args - Arguments to update many RaceHorses.
   * @example
   * // Update many RaceHorses
   * const raceHorse = await prisma.raceHorse.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more RaceHorses and only return the `raceId`
   * const raceHorseWithRaceIdOnly = await prisma.raceHorse.updateManyAndReturn({
   *   select: { raceId: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends RaceHorseUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, RaceHorseUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one RaceHorse.
   * @param {RaceHorseUpsertArgs} args - Arguments to update or create a RaceHorse.
   * @example
   * // Update or create a RaceHorse
   * const raceHorse = await prisma.raceHorse.upsert({
   *   create: {
   *     // ... data to create a RaceHorse
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RaceHorse we want to update
   *   }
   * })
   */
  upsert<T extends RaceHorseUpsertArgs>(args: Prisma.SelectSubset<T, RaceHorseUpsertArgs<ExtArgs>>): Prisma.Prisma__RaceHorseClient<runtime.Types.Result.GetResult<Prisma.$RaceHorsePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of RaceHorses.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseCountArgs} args - Arguments to filter RaceHorses to count.
   * @example
   * // Count the number of RaceHorses
   * const count = await prisma.raceHorse.count({
   *   where: {
   *     // ... the filter for the RaceHorses we want to count
   *   }
   * })
  **/
  count<T extends RaceHorseCountArgs>(
    args?: Prisma.Subset<T, RaceHorseCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RaceHorseCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RaceHorse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RaceHorseAggregateArgs>(args: Prisma.Subset<T, RaceHorseAggregateArgs>): Prisma.PrismaPromise<GetRaceHorseAggregateType<T>>

  /**
   * Group by RaceHorse.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RaceHorseGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RaceHorseGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RaceHorseGroupByArgs['orderBy'] }
      : { orderBy?: RaceHorseGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RaceHorseGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRaceHorseGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RaceHorse model
 */
readonly fields: RaceHorseFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RaceHorse.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RaceHorseClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  race<T extends Prisma.RaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RaceDefaultArgs<ExtArgs>>): Prisma.Prisma__RaceClient<runtime.Types.Result.GetResult<Prisma.$RacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  horse<T extends Prisma.HorseDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.HorseDefaultArgs<ExtArgs>>): Prisma.Prisma__HorseClient<runtime.Types.Result.GetResult<Prisma.$HorsePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RaceHorse model
 */
export interface RaceHorseFieldRefs {
  readonly raceId: Prisma.FieldRef<"RaceHorse", 'Int'>
  readonly horseId: Prisma.FieldRef<"RaceHorse", 'Int'>
  readonly position: Prisma.FieldRef<"RaceHorse", 'Int'>
}
    

// Custom InputTypes
/**
 * RaceHorse findUnique
 */
export type RaceHorseFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * Filter, which RaceHorse to fetch.
   */
  where: Prisma.RaceHorseWhereUniqueInput
}

/**
 * RaceHorse findUniqueOrThrow
 */
export type RaceHorseFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * Filter, which RaceHorse to fetch.
   */
  where: Prisma.RaceHorseWhereUniqueInput
}

/**
 * RaceHorse findFirst
 */
export type RaceHorseFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * Filter, which RaceHorse to fetch.
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaceHorses to fetch.
   */
  orderBy?: Prisma.RaceHorseOrderByWithRelationInput | Prisma.RaceHorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RaceHorses.
   */
  cursor?: Prisma.RaceHorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaceHorses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaceHorses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RaceHorses.
   */
  distinct?: Prisma.RaceHorseScalarFieldEnum | Prisma.RaceHorseScalarFieldEnum[]
}

/**
 * RaceHorse findFirstOrThrow
 */
export type RaceHorseFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * Filter, which RaceHorse to fetch.
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaceHorses to fetch.
   */
  orderBy?: Prisma.RaceHorseOrderByWithRelationInput | Prisma.RaceHorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RaceHorses.
   */
  cursor?: Prisma.RaceHorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaceHorses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaceHorses.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RaceHorses.
   */
  distinct?: Prisma.RaceHorseScalarFieldEnum | Prisma.RaceHorseScalarFieldEnum[]
}

/**
 * RaceHorse findMany
 */
export type RaceHorseFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * Filter, which RaceHorses to fetch.
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RaceHorses to fetch.
   */
  orderBy?: Prisma.RaceHorseOrderByWithRelationInput | Prisma.RaceHorseOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RaceHorses.
   */
  cursor?: Prisma.RaceHorseWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RaceHorses from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RaceHorses.
   */
  skip?: number
  distinct?: Prisma.RaceHorseScalarFieldEnum | Prisma.RaceHorseScalarFieldEnum[]
}

/**
 * RaceHorse create
 */
export type RaceHorseCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * The data needed to create a RaceHorse.
   */
  data: Prisma.XOR<Prisma.RaceHorseCreateInput, Prisma.RaceHorseUncheckedCreateInput>
}

/**
 * RaceHorse createMany
 */
export type RaceHorseCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RaceHorses.
   */
  data: Prisma.RaceHorseCreateManyInput | Prisma.RaceHorseCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * RaceHorse createManyAndReturn
 */
export type RaceHorseCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * The data used to create many RaceHorses.
   */
  data: Prisma.RaceHorseCreateManyInput | Prisma.RaceHorseCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * RaceHorse update
 */
export type RaceHorseUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * The data needed to update a RaceHorse.
   */
  data: Prisma.XOR<Prisma.RaceHorseUpdateInput, Prisma.RaceHorseUncheckedUpdateInput>
  /**
   * Choose, which RaceHorse to update.
   */
  where: Prisma.RaceHorseWhereUniqueInput
}

/**
 * RaceHorse updateMany
 */
export type RaceHorseUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RaceHorses.
   */
  data: Prisma.XOR<Prisma.RaceHorseUpdateManyMutationInput, Prisma.RaceHorseUncheckedUpdateManyInput>
  /**
   * Filter which RaceHorses to update
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * Limit how many RaceHorses to update.
   */
  limit?: number
}

/**
 * RaceHorse updateManyAndReturn
 */
export type RaceHorseUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * The data used to update RaceHorses.
   */
  data: Prisma.XOR<Prisma.RaceHorseUpdateManyMutationInput, Prisma.RaceHorseUncheckedUpdateManyInput>
  /**
   * Filter which RaceHorses to update
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * Limit how many RaceHorses to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * RaceHorse upsert
 */
export type RaceHorseUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * The filter to search for the RaceHorse to update in case it exists.
   */
  where: Prisma.RaceHorseWhereUniqueInput
  /**
   * In case the RaceHorse found by the `where` argument doesn't exist, create a new RaceHorse with this data.
   */
  create: Prisma.XOR<Prisma.RaceHorseCreateInput, Prisma.RaceHorseUncheckedCreateInput>
  /**
   * In case the RaceHorse was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RaceHorseUpdateInput, Prisma.RaceHorseUncheckedUpdateInput>
}

/**
 * RaceHorse delete
 */
export type RaceHorseDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
  /**
   * Filter which RaceHorse to delete.
   */
  where: Prisma.RaceHorseWhereUniqueInput
}

/**
 * RaceHorse deleteMany
 */
export type RaceHorseDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RaceHorses to delete
   */
  where?: Prisma.RaceHorseWhereInput
  /**
   * Limit how many RaceHorses to delete.
   */
  limit?: number
}

/**
 * RaceHorse without action
 */
export type RaceHorseDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RaceHorse
   */
  select?: Prisma.RaceHorseSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RaceHorse
   */
  omit?: Prisma.RaceHorseOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RaceHorseInclude<ExtArgs> | null
}
