
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const BetType = {
  WIN: 'WIN',
  PLACE: 'PLACE',
  SHOW: 'SHOW',
  EXACTA: 'EXACTA',
  TRIFECTA: 'TRIFECTA'
} as const

export type BetType = (typeof BetType)[keyof typeof BetType]
